# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_release_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.AddField(
            model_name='release',
            name='track',
            field=models.ManyToManyField(to='core.Track'),
        ),
    ]
