# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20151207_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='barcode',
            field=models.CharField(max_length=13),
        ),
    ]
