# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20151208_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='barcode',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='track',
            field=models.ManyToManyField(blank=True, null=True, to='core.Track'),
        ),
    ]
