# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20151208_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='track',
            field=models.ManyToManyField(blank=True, to='core.Track'),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Artist'),
        ),
    ]
