# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20151209_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='artist',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Artist'),
            preserve_default=False,
        ),
    ]
